### ISSUE TITLE
New Character by pressing reload after creating one

### ISSUE THREAD

**Issue by TanConan** [GragonGit/Gragons-TTRPG-Tool#9]
### Issue
You can create a lot of new characters if you reload your browser while viewing the newly created character.
### How to reproduce
1. Create a new character and get redirected to the detail page of this new character.
2. Reload the page a few times.
3. Go back to the main page by clicking the house Icon on the bottom right.

You will see a few new characters that aren't supposed to be created!

**Comment by GragonGit** [comment]
Fixed [here](https://github.com/GragonGit/Gragons-TTRPG-Tool/commit/cb1d3cb2ad1b909805807bbb0b0b985c3d37d6d4) #cb1d3cb
